export const WS_ACTIONS = {
   CONNECTED: "CONNECTED",
   SUBSCRIBE_SHOWTIME: "SUBSCRIBE_SHOWTIME",
   SEAT_SELECTED: "SEAT_SELECTED",
   SEAT_RELEASED: "SEAT_RELEASED",
   SEAT_BOOKED: "SEAT_BOOKED",
   PONG: "PONG",
   PING: "PING",
};

export const SEAT_STATUS = {
   AVAILABLE: "AVAILABLE",
   LOCKED: "LOCKED",
   BOOKED: "BOOKED",
};
